name: Coverage

on:
  push:
    branches:
      - master  # Change 'main' to your main branch name
  pull_request:
    branches:
      - master  # Change 'main' to your main branch name

jobs:
  test:
    runs-on: ubuntu-latest  # Use any runner you prefer

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Replace '3.x' with your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install
        pipenv 

    - name: coverage
      run: pipenv run make coverage

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
